version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@11.6
  shellcheck: circleci/shellcheck@3.1

filters: &filters
  tags:
    only: /.*/

workflows:
  main-wf:
    jobs:
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          exclude: "RC001,RC003,RC006,RC009"
          filters: *filters
      - shellcheck/check:
          filters: *filters
      - orb-tools/publish:
          orb-name: felicianotech/aptly
          vcs-type: << pipeline.project.type >>
          requires:
            - orb-tools/review
            - orb-tools/pack
            - shellcheck/check
          context: circleci-ctx
          filters: *filters
